name: .NET CI

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
      OPENAI_API_KEY: "test"
      AWS__AccessKey: "test"
      AWS__SecretKey: "test"
      AWS__ServiceURL: "http://localhost"
      Supabase__Url: "http://localhost"
      Supabase__Key: "test"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore API
        run: dotnet restore apps/api/Aroundtheway.Api.csproj

      - name: Restore Tests
        run: dotnet restore apps/api/Aroundtheway.Api.Tests/Aroundtheway.Api.Tests.csproj

      - name: Build API (Release)
        run: dotnet build apps/api/Aroundtheway.Api.csproj -c Release --no-restore

      - name: Build Tests (Release)
        run: dotnet build apps/api/Aroundtheway.Api.Tests/Aroundtheway.Api.Tests.csproj -c Release --no-restore

      # Run tests
      - name: Test
        run: dotnet test apps/api/Aroundtheway.Api.Tests/Aroundtheway.Api.Tests.csproj -c Release --no-build -v n
